const courses = {
    ee: {
        communication: [
            {
                name: 'Information Theory and Coding',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=40',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Computer Networks (CS)',
                level: 300,
                hours: '3-0-2',
                credits: 4.5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=18',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Microwave Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=45',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Cellular Communication Networks',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=44',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Satellite Communications',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=43',
                semesterAvailability: ['even'],
            },
            {
                name: 'Spread Spectrum Communications',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=41',
                semesterAvailability: ['even', 'odd'],
            },
            {
                name: 'Optical Communication Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=42',
                semesterAvailability: ['even'],
            },
        ],
        signal_processing: [
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Speech Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=48',
                semesterAvailability: ['even'],
            },
            {
                name: 'Signal Compression',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=47',
                semesterAvailability: ['even'],
            },
            {
                name: 'System Identification',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=49',
                semesterAvailability: ['even'],
            },
        ],
        control_engineering: [
            {
                name: 'Modern Control',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=51',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Nonlinear and Adaptive Control',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=52',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Robust and Optimal Control',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=53',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Foundations of Cyber Physical Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=54',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Introduction to Robotics (IDRP)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course1',
                semesterAvailability: ['even'],
            },
        ],
        devices_circuits: [
            {
                name: 'VLSI Design',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=56',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Biosensors',
                level: 300,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=57',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Integrated Circuit Technology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Sensors and Actuators',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=59',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'CAD for VLSI',
                level: 700,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=58',
                semesterAvailability: ['even'],
            },
            {
                name: 'Physics and Modeling of MOS Transistor',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=60',
                semesterAvailability: ['odd','even'],
            },
        ],
        computing_systems: [
            {
                name: 'Deep Learning (AI)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=25',
                semesterAvailability: ['even'], 
            },
            {
                name: 'High Level Synthesis (CS)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Real-Time Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Reconfigurable Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=63',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Pervasive and Mobile Computing (CS)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=95',
                semesterAvailability: ['even'],
            },
        ],
        power_engineering: [
            {
                name: 'Measurement and Instrumentation',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=69',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Power System Analysis and Stability',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=65',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Power System Operation and Control ',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=66',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Power Electronics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=67',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Industrial Drives',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=68',
                semesterAvailability: ['even'],
            },
        ],
    },
    cse: {
        theory_algorithms: [
            {
                name: 'Randomized Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=101',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Approximation Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=56',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Complexity Theory',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=62',
                semesterAvailability: ['even'],
            },
            {
                name: 'Advanced Data Structures',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=29',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Quantum Computing',
                level: 400,
                hours: '3-0-2',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Graph-theoretic Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=83',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Parameterized Complexity',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=99',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Optimization (Math)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=27',
                semesterAvailability: ['odd'],
            },
        ],
        hardware: [
            {
                name: 'High-level Synthesis (EE/CS)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=87',
                semesterAvailability: ['even','odd'], 
            },
            {
                name: 'Embedded Systems (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=36',
                semesterAvailability: ['even'], 
            },
            {
                name: 'VLSI Design (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=56',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Hardware Software Co-Design (CS)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=85',
                semesterAvailability: ['even'], 
            },
        ],
        systems: [
            {
                name: 'Software Testing and Quality Assurance',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=109',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Distributed Database Systems',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=76',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Distributed Systems',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=32',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Mobile and Pervasive Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=95',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Virtualization and Cloud Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=116',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Compiler Design',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=61',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Software Maintenance',
                level: 400,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=36',
                semesterAvailability: ['odd','even'], 
            },
        ],
        network_security: [
            {
                name: 'Introduction to Wireless Ad hoc Network',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=91',
                semesterAvailability: ['odd','even'],
            },
            {
                name: '5G Mobile Networks',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=96',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Software Defined Networks',
                level: 700,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=108',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Intelligent Radio Networks (EE)',
                level: 700,
                hours: '3-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=82',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Data Communication Networks (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=35',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Cryptography and Network Security (CS/EE) ',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Introduction to Blockchain',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=90',
                semesterAvailability: ['odd'], 
            },
        ],
        ai_ml: [
            {
                name: 'Deep Learning',
                level: 400,
                hours: '3-0-2',
                credits: 4.5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=25',
                semesterAvailability: ['even'],
            },
            {
                name: 'Artificial Intelligence',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Advanced Machine Learning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=53',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Dependable Artificial Intelligences',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=26',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Information Retrieval',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=88',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Autonomous Systems (IDRP) ',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=58',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Ethics, Policy, Law and Regulation in AI',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=80',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Planning and Decision making for Robots (IDRP)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd','even'], 
            },
        ],
        speech_text_vision: [
            {
                name: 'Natural Language Understanding',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=97',
                semesterAvailability: ['even'],
            },
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Vision',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=68',
                semesterAvailability: ['even'],
            },
            {
                name: 'Computer Graphics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=66',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Speech Understanding',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=110',
                semesterAvailability: ['odd','even'], 
            },
        ],
        social_computing: [
            {
                name: 'Social Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=104',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Sustainable Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=111',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'ICT for Development',
                level: 400,
                hours: '2-0-0',
                credits: 5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=33',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Machine Learning for Epidemiology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=92',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Health Informatics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=86',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Social Choice',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=65',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Computational Cognition & Behavior Modelling',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=30',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Social Networks',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=105',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Ethics, policy, law and regulations in AI',
                level: 400,
                hours: '0-0-2',
                credits: 1,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=80',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Crowd-sourcing and human computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=69',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Environmental Informatics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=79',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Microeconomics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=63',
                semesterAvailability: ['odd'], 
            },
        ],
    },
    me: {
        design: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        manufacturing: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        thermofluids: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'],
            },
        ],
    },
    ch: {
        chem_eng_design: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'],
            },
        ],
        process_eng_int: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        cfie: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'],
            },
        ],
        sust: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        molec_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        biochem_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
    },
    mt: {
        struct_mat: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        func_mat: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        comp_mat_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        process_met: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
    },
    ci: {
        sit: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        geo_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        env_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        trans_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        cons_infra: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        struct_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        res_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        infra_sys: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
    },
    bb: {
        omics: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        biom_eng: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        csb: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        bioimaging: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        biosensors: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        mssd: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        ddd: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'],
            },
        ],
    },
    ai: {
        ai_ml: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        robot: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        socio_digital: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        sci_intell: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        applications: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        cps_iot: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'], 
            },
        ],
        data_dis: [
            {
                name: 'Social Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd'],
            },
        ],
    },
};

export default courses;