const courses = {
    ee: {
        communication: [
            {
                name: 'Information Theory and Coding',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=40',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Computer Networks (CS)',
                level: 300,
                hours: '3-0-2',
                credits: 4.5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=18',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Microwave Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=45',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Cellular Communication Networks',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=44',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Satellite Communications',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=43',
                semesterAvailability: ['even'],
            },
            {
                name: 'Spread Spectrum Communications',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=41',
                semesterAvailability: ['even', 'odd'],
            },
            {
                name: 'Optical Communication Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=42',
                semesterAvailability: ['even'],
            },
        ],
        signal_processing: [
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=50',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Speech Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=48',
                semesterAvailability: ['even'],
            },
            {
                name: 'Signal Compression',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=47',
                semesterAvailability: ['even'],
            },
            {
                name: 'System Identification',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=49',
                semesterAvailability: ['even'],
            },
        ],
        control_engineering: [
            {
                name: 'Modern Control',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=51',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Nonlinear and Adaptive Control',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=52',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Robust and Optimal Control',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=53',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Foundations of Cyber Physical Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=54',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Introduction to Robotics (IDRP)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://shorturl.at/lBJS0',
                semesterAvailability: ['even'],
            },
        ],
        devices_circuits: [
            {
                name: 'VLSI Design',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=56',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Biosensors',
                level: 300,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=57',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Integrated Circuit Technology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Sensors and Actuators',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=59',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'CAD for VLSI',
                level: 700,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=58',
                semesterAvailability: ['even'],
            },
            {
                name: 'Physics and Modeling of MOS Transistor',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=60',
                semesterAvailability: ['odd','even'],
            },
        ],
        computing_systems: [
            {
                name: 'Deep Learning (AI)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=25',
                semesterAvailability: ['even'], 
            },
            {
                name: 'High Level Synthesis (CS)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Real-Time Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Reconfigurable Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=63',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Pervasive and Mobile Computing (CS)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=95',
                semesterAvailability: ['even'],
            },
        ],
        power_engineering: [
            {
                name: 'Measurement and Instrumentation',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=69',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Power System Analysis and Stability',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=65',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Power System Operation and Control ',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=66',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Power Electronics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=67',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Industrial Drives',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=68',
                semesterAvailability: ['even'],
            },
        ],
    },
    cse: {
        theory_algorithms: [
            {
                name: 'Randomized Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=101',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Approximation Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=56',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Complexity Theory',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=62',
                semesterAvailability: ['even'],
            },
            {
                name: 'Advanced Data Structures',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=29',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Quantum Computing',
                level: 400,
                hours: '3-0-2',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Graph-theoretic Algorithms',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=83',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Parameterized Complexity',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=99',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Optimization (Math)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=27',
                semesterAvailability: ['odd'],
            },
        ],
        hardware: [
            {
                name: 'High-level Synthesis (EE/CS)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=87',
                semesterAvailability: ['even','odd'], 
            },
            {
                name: 'Embedded Systems (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=36',
                semesterAvailability: ['even'], 
            },
            {
                name: 'VLSI Design (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=56',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Hardware Software Co-Design (CS)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=85',
                semesterAvailability: ['even'], 
            },
        ],
        systems: [
            {
                name: 'Software Testing and Quality Assurance',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=109',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Distributed Database Systems',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=76',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Distributed Systems',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=32',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Mobile and Pervasive Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=95',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Virtualization and Cloud Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=116',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Compiler Design',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=61',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Software Maintenance',
                level: 400,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=36',
                semesterAvailability: ['odd','even'], 
            },
        ],
        network_security: [
            {
                name: 'Introduction to Wireless Ad hoc Network',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=91',
                semesterAvailability: ['odd','even'],
            },
            {
                name: '5G Mobile Networks',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=96',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Software Defined Networks',
                level: 700,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=108',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Intelligent Radio Networks (EE)',
                level: 700,
                hours: '3-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=82',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Data Communication Networks (EE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=35',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Cryptography and Network Security (CS/EE) ',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=57',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Introduction to Blockchain',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=90',
                semesterAvailability: ['odd'], 
            },
        ],
        ai_ml: [
            {
                name: 'Deep Learning',
                level: 400,
                hours: '3-0-2',
                credits: 4.5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=25',
                semesterAvailability: ['even'],
            },
            {
                name: 'Artificial Intelligence',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Advanced Machine Learning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=53',
                semesterAvailability: ['odd'],
            },
            {
                name: 'Dependable Artificial Intelligences',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=26',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Information Retrieval',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=88',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Autonomous Systems (IDRP) ',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=58',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Ethics, Policy, Law and Regulation in AI',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=80',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Planning and Decision making for Robots (IDRP)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3',
                semesterAvailability: ['odd','even'], 
            },
        ],
        speech_text_vision: [
            {
                name: 'Natural Language Understanding',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=97',
                semesterAvailability: ['even'],
            },
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=50',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Vision',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=68',
                semesterAvailability: ['even'],
            },
            {
                name: 'Computer Graphics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=66',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Speech Understanding',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=110',
                semesterAvailability: ['odd','even'], 
            },
        ],
        social_computing: [
            {
                name: 'Social Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=104',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Sustainable Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=111',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'ICT for Development',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=33',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Machine Learning for Epidemiology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=92',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Health Informatics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=86',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Social Choice',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=65',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Computational Cognition & Behavior Modelling',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=30',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Social Networks',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=105',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Ethics, policy, law and regulations in AI',
                level: 400,
                hours: '0-0-2',
                credits: 1,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=80',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Crowd-sourcing and human computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=69',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Environmental Informatics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=79',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Microeconomics',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=63',
                semesterAvailability: ['odd'], 
            },
        ],
    },
    //Mechanical Engineering
    me: {
        design: [
            {
                name: 'Introduction to Acoustics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=74',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Mechanical Vibrations',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=79',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Computer aided Design',
                level: 400,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=76',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Mechatronics',
                level: 600,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=81',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Principles of Biomechanics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Finite Element Methods and Applications',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=82',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Introduction to Robotics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://shorturl.at/lBJS0',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Embedded Systems',
                level: 300,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/EE/2.%20B.Tech%20EE_24092020.pdf#page=36',
                semesterAvailability: ['even'], 
            },

        ],
        manufacturing: [
            {
                name: 'Tool Design',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=60',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Applied Ergonomics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=61',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Micro-Nano Manufacturing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=62',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Design and Manufacturing of Bio Materials',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Integrated Manufacturing',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=64',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Design for Manufacturing',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=65',
                semesterAvailability: ['odd','even'], 
            },
        ],
        thermofluids: [
            {
                name: 'Turbomachinery',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=49',
                semesterAvailability: ['even'],
            },
            {
                name: 'Refrigeration and Airconditioning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Power Plant Engineering',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=51',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Porous media flows and applications',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=56',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Solar Thermal Systems',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=53',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Computational Fluid Dynamics and Heat Transfer',
                level: 700,
                hours: '3-1-0',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf',
                semesterAvailability: ['even'],
            },
        ],
    },
    //Chemical engineering
    ch: {
        chem_eng_design: [
            {
                name: 'Industrial Management and Safety for Chemical Engineers',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=39',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Product Design in Chemical Engineering',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=40',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Unit Operations',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=41',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Membrane Technology',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=42',
                semesterAvailability: ['odd','even'],
            },
        ],
        process_eng_int: [
            {
                name: 'Applications of Artificial Intelligence in Chemical Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=43',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Petrochemical Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=45',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Petroleum Refinery Process Modelling',
                level: 400,
                hours: '1-0-2',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=46',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Basics of Reliability and Maintainability Engineering for System Safety',
                level: 400,
                hours: '3-1-0',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=47',
                semesterAvailability: ['odd','even'], 
            },
        ],
        cfie: [
            {
                name: 'Introduction to Complex Fluids',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=48',
                semesterAvailability: ['even'],
            },
            {
                name: 'Interfacial Engineering in Soft Matter',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=49',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Bioprinting',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=50',
                semesterAvailability: ['odd','even'],
            },
            {
                name: '3-D Printing: Material Processing and Properties',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=51',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Introductory Principles in Polymer Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=53',
                semesterAvailability: ['odd'],
            },
        ],
        sust: [
            {
                name: 'Solid Waste Management',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=54',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Air Pollution Control technology',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=55',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Processing of Rare-earth and Radioactive Materials',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=56',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Energy Resources',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=57',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Waste Water Treatment',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=58',
                semesterAvailability: ['odd','even'], 
            },
        ],
        molec_eng: [
            {
                name: 'Molecular Transport Phenomena',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=59',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Fluid-Like Structures and SelfAssembling Systems',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=60',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Organic Molecules, Complexes and Polymers for Electronics and Optoelectronics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=61',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Molecular Thermodynamics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
        ],
        biochem_eng: [
            {
                name: 'Biochemical Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=63',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Bioprocess Technology',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=64',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Bio-Transport Phenomena',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=65',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Biochemical Separation Processes',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=66',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Bioreactors',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=67',
                semesterAvailability: ['odd','even'], 
            },
        ],
    },
    // Material Engineering
    mt: {
        struct_mat: [
            {
                name: 'Processing-Microstructure and Properties of Steels',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=35',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Degradation and Failure of Materials',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=36',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Composites',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=37',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Polymeric Materials and Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=38',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Ceramics and Glass',
                level: 400,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=39',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Casting and Solidification',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=41',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Metallurgy of Joining',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=42',
                semesterAvailability: ['even'], 
            },
            {
                name: 'High Temperature Materials',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Digital Fabrication',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=44',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Smart Manufacturing',
                level: 300,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=47',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Additive Manufacturing',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Aided Design',
                level: 400,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=76',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Design of Machine Elements',
                level: 300,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=35',
                semesterAvailability: ['odd','even'], 
            },
        ],
        func_mat: [
            {
                name: 'Battery Materials',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=43',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: '3D Printing: Material Processing and Properties',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=45',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Lithium ion Batteries',
                level: 400,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=47',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Surface Engineering',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=49',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Synthesis and Processing of Semiconductors and 2D materials',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=50',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Functional Ceramics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=53',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Magnetism and Magnetic Materials',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=55',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Nanoscience',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Biomaterials Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=52',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Cell-Material Interaction',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=36',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Tissue Engineering (BSBE)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=37',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Interfacial Engineering in Soft Matter (CHE)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cml/UG_Curriculum_document-2020-11-11-17-01-pm.pdf#page=49',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Quantum Mechanics (PHY)',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://shorturl.at/isILO',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Advanced Condensed Matter Physics (PHY)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://rb.gy/r8dcw',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Energy Harvesting Technologies (PHY)',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://rb.gy/1u74o',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Physics of Solar Cells (PHY)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://rb.gy/ywwi6',
                semesterAvailability: ['odd','even'], 
            },
        ],
        comp_mat_eng: [
            {
                name: 'Computational Thermodynamics',
                level: 400,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=56',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Modelling of Metallurgical Processes',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Machine Learning for Materials Design',
                level: 700,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'First-Principles Calculations',
                level: 700,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Phase field modelling',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Industry 4.0: Applications in Metallurgical and Materials Engineering',
                level: 700,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Introduction to Internet of Things (EE)',
                level: 700,
                hours: '1-0-0',
                credits: 1,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Finite Element Methods (ME)',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/UG/ME/1%20B.Tech%20ME%20Curriculum%20structure.pdf#page=82',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Artificial Intelligence (CSE)',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=62',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Deep Learning (CSE) ',
                level: 400,
                hours: '3-0-3',
                credits: 4.5,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=25',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Optimization (Offered by MA)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=27',
                semesterAvailability: ['odd'], 
            },
        ],
        process_met: [
            {
                name: 'Mineral Beneficiation',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=57',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Kinetics of Metallurgical Processes',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=58',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Principles of Process Metallurgy',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=59',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Hydrometallurgy',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=60',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Electrometallurgy',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=61',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Secondary and Special Steelmaking',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf#page=62',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Processing of Rare Earth and Radioactive Materials (CH)',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Fluid Dynamics (CH)',
                level: 700,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/mat/B.Tech.%20Curriculum_document-2020-10-07-12-26-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },

        ],
    },
    //Civil Engineering
    ci: {
        sit: [
            {
                name: 'AI/ML in Infrastructure Engineering',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=109',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Building Services',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=115',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Intelligent Buildings',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=113',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Surveillance and Security of Infrastructures',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=103',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Cyber-Physical Systems for Infrastructure',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=107',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Digital Twin and Asset management',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=105',
                semesterAvailability: ['odd','even'], 
            },
        ],
        geo_eng: [
            {
                name: 'Geology for Civil Engineers',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=91',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Ground Improvement Techniques',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=93',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Introduction to Soil Dynamics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=95',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Advanced Geotechnical Engineering',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=97',
                semesterAvailability: ['odd','even'], 
            },
        ],
        env_eng: [
            {
                name: 'Air pollution and Control',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=99',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Mathematical Modelling in Environmental System',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=111',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Industrial Waste: Control and Utilization',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=101',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Environmental Biotechnology and Bioremediation',
                level: 700,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=117',
                semesterAvailability: ['odd','even'], 
            },
        ],
        trans_eng: [
            {
                name: 'Highway Geometric Design',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=83',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Pavement Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=85',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Traffic System and ITS',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=87',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Urban Transportation Planning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=89',
                semesterAvailability: ['odd','even'], 
            },
        ],
        cons_infra: [
            {
                name: 'Concrete Technology',
                level: 400,
                hours: '3-0-3',
                credits: 4.5,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=77',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Infrastructure Planning and Management',
                level: 400,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=123',
                semesterAvailability: ['odd'], 
            },
        ],
        struct_eng: [
            {
                name: 'Steel Structure Design',
                level: 400,
                hours: '3-1-0',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=67',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Advanced Structural Design',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=69',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Dynamics of Structure',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=71',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Finite Element Method',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=73',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Prestressed concrete structures',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=79',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Prefabricated structures',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=81',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Earthquake Engineering',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=75',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Introduction to Structural Health monitoring',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=121',
                semesterAvailability: ['odd','even'], 
            },
        ],
        res_eng: [
            {
                name: 'Environmental Hydrology',
                level: 700,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=119',
                semesterAvailability: ['odd'], 
            },
        ],
        infra_sys: [
            {
                name: 'Introduction to Power Infrastructure Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=125',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Thermal and nuclear power infrastructure Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=127',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Infrastructure planning and design for rail and air transport',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=129',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Infrastructure planning and design of ports and harbours',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=131',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'IT and Telecom Infrastructure',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=133',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Green Building and Sustainable Materials',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/cvl/UG_Civil%20and%20Infrastructure%20Engineering%20Curriculum%20_document-2020-10-03-20-04-pm.pdf#page=135',
                semesterAvailability: ['even'], 
            },
        ],
    },
    //Biosciences and Bioengineering
    bb: {
        omics: [
            {
                name: 'Microbiomes and Metagenomics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=32',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Computational Methods for Multiomics',
                level: 400,
                hours: '3-0-2',
                credits: 4,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Microarray Data Analysis',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=34',
                semesterAvailability: ['odd','even'], 
            },
        ],
        biom_eng: [
            {
                name: 'Cell-material Interactions',
                level: 300,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=36',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Tissue Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=37',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Therapeutic Delivery Systems',
                level: 400,
                hours: '2-0-0',
                credits: 2,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=38',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Principles of Biomechanics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Additive Manufacturing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Bio-transport Phenomena',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=39',
                semesterAvailability: ['odd','even'], 
            },
        ],
        csb: [
            {
                name: 'Mathematical Biology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Algorithms in Biology',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=41',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Modelling Biological Systems',
                level: 300,
                hours: '2-0-2',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=42',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Design of Experiments',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
        ],
        bioimaging: [
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=50',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Bio-image Computing',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Electron Microscopy for Biology',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Special topics on biomedical imaging',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
        ],
        biosensors: [
            {
                name: 'Whole Cell based Biosensors',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=45',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Microsystems Fabrication Technology',
                level: 700,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Chemosensors',
                level: 600,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf',
                semesterAvailability: ['odd','even'], 
            },
        ],
        mssd: [
            {
                name: 'Microbial Remediation and Environmental Biotechnology',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=47',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Microbes in Food and Sustainable Agriculture',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=48',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Bioenergy',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=49',
                semesterAvailability: ['odd'], 
            },
        ],
        ddd: [
            {
                name: 'Principles of Drug Discovery',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=51',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Medicinal Chemistry',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=52',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Viral Infection and Antiviral Drug Development',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://iitj.ac.in/uploaded_docs/dept_upload/bio/curriculum_document-2020-10-03-22-20-pm.pdf#page=53',
                semesterAvailability: ['even'],
            },
        ],
    },
    ai: {
        ai_ml: [
            {
                name: 'Advanced Artificial Intelligence',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=33',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Advanced Machine Learning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=32',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Resource Constrained Artificial Intelligence',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Scalable Machine Learning',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Learning Theory',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Information Retrieval',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=36',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Graph Theoretic Algorithms',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Stream Analytics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=39',
                semesterAvailability: ['odd','even'], 
            },
        ],
        robot: [
            {
                name: 'Introduction to Robotics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://shorturl.at/lBJS0',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Planning and Decision Making of Robots',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Multi-Agent Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Autonomous Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/curriculum/CSE-Courses-Details.pdf#page=58',
                semesterAvailability: ['even'], 
            },
        ],
        socio_digital: [
            {
                name: 'Multimodal Interfaces',
                level: 400,
                hours: '0-0-2',
                credits: 2,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Introduction to Haptics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Introduction to AR and VR',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Advanced Human-Machine Interaction',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Social Networks',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://syllabus-link.com/course3https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=38',
                semesterAvailability: ['odd','even'], 
            },
        ],
        sci_intell: [
            {
                name: 'Computational Neuroscience',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Connectomics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Bioimaging',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
        ],
        applications: [
            {
                name: 'Digital Image Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=50',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Vision',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=40',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Natural Language Understanding',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=34',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Speech Understanding',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=51',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computational Linguistics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Advanced Biometrics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=42',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Computer Graphics',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=43',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Video Processing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=49',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'Animation',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
            {
                name: 'GPU Programming',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
        ],
        cps_iot: [
            {
                name: 'Introduction to Cyber Physical Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd'], 
            },
            {
                name: 'Embedded Systems Design',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Security in CPS',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Edge and Fog Computing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['even'], 
            },
            {
                name: 'Real Time Systems',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'], 
            },
        ],
        data_dis: [
            {
                name: 'Introduction to Space Science',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Reliability Engineering and Life Testing',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=55',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Introduction to Game Theory',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=54',
                semesterAvailability: ['even'],
            },
            {
                name: 'Nonlinear Dynamics and Chaos',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=59',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Differential Geometry',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=58',
                semesterAvailability: ['odd','even'],
            },
            {
                name: 'Introduction to Financial Engineering',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf#page=53',
                semesterAvailability: ['even'],
            },
            {
                name: 'Computational Chemistry',
                level: 400,
                hours: '3-0-0',
                credits: 3,
                syllabus: 'https://cse.iitj.ac.in/images/pdf/BTech_AIDE_24092020.pdf',
                semesterAvailability: ['odd','even'],
            },
        ],
    },
};

export default courses;